spring.datasource.url=jdbc:postgresql://operator_db_p4qx_user:Glyrz6goR5KHkK1Me5WSkYhMTrcXzepo@dpg-dabgodn10e5c73fvh020-a/operator_db_p4qx
spring.datasource.username=operator_db_p4qx_user
spring.datasource.password=Glyrz6goR5KHkK1Me5WSkYhMTrcXzepo
spring.jpa.hibernate.ddl-auto=update
